### PR TITLE
add code for password validator

### PR DESCRIPTION
**Pull request by Samir70**
For the peer review part of the challenge in chapter 1 of the ruby_foundations module at Makers Academy

### CODE REVIEW

**Comment by SamuelHunt2002** [comment]
Really nice one line solution. My only suggestion would be to maybe instead of using .count, use =~ to check via RegEx. I guess it's just personal preference and .count works fine here as well.

So it would look something like 

 return password.length > 7 &&  password =~ /[!@$%&]+/

**Comment by SamuelHunt2002** [comment]
The other suggestion I have is possibly to put each condition in parentheses for readability? 

But these are very minor suggestions and It is really good In its current form.

**Comment by Samir70** [comment]
I have tried to improve the readability. But, rather than use brackets, I decided to go all out and write two helper methods.

**Comment by SamuelHunt2002** [comment]
Looks perfect!

**Pull request merged**
